version: "3"

services:
  front-end:
    depends_on:
      - back-end
    container_name: react-nginx
    build: ./front-end
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
  back-end:
    depends_on:
      - db
    container_name: python-api
    build: ./back-end
    links:
      - db
    ports:
      - "5000:5000"
    restart: on-failure
  db:
    container_name: database
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "AD"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    